//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.UI.AutoRotation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AutoRotationUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutoRotationUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.UI.AutoRotation.AutoRotationUI", typeof(AutoRotationUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass Only in Combat for Quest Targets.
        /// </summary>
        internal static string Checkbox_BypassQuestTargets {
            get {
                return ResourceManager.GetString("Checkbox_BypassQuestTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass When Combo Suggests Self-Use Action.
        /// </summary>
        internal static string Checkbox_BypassSelfUse {
            get {
                return ResourceManager.GetString("Checkbox_BypassSelfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto-Rotation.
        /// </summary>
        internal static string Checkbox_EnableAutoRotation {
            get {
                return ResourceManager.GetString("Checkbox_EnableAutoRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only in Combat.
        /// </summary>
        internal static string Checkbox_OnlyInCombat {
            get {
                return ResourceManager.GetString("Checkbox_OnlyInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Auto-Mode outside of combat unless you&apos;re within range of a quest target..
        /// </summary>
        internal static string HelpText_BypassQuestTargets {
            get {
                return ResourceManager.GetString("HelpText_BypassQuestTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many jobs have an out of combat action that can be used, for example, {0} or {1}. This will allow these to be used without being in combat..
        /// </summary>
        internal static string HelpText_BypassSelfUse {
            get {
                return ResourceManager.GetString("HelpText_BypassSelfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where you can configure the parameters in which Auto-Rotation will operate.
        ///Features marked with an &apos;Auto-Mode&apos; checkbox are able to be used with Auto-Rotation..
        /// </summary>
        internal static string Info_Header {
            get {
                return ResourceManager.GetString("Info_Header", resourceCulture);
            }
        }
    }
}
