//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.UI.Features {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeaturesUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeaturesUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.UI.Features.FeaturesUI", typeof(FeaturesUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled due to update.
        /// </summary>
        internal static string DisabledDueToUpdate {
            get {
                return ResourceManager.GetString("DisabledDueToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip your job stone to re-unlock features..
        /// </summary>
        internal static string EquipJobStone {
            get {
                return ResourceManager.GetString("EquipJobStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Replacing is Disabled in Settings! PvP Combos will not work!.
        /// </summary>
        internal static string pvpActionReplacingWarning {
            get {
                return ResourceManager.GetString("pvpActionReplacingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Rotation is unavailable for PvP..
        /// </summary>
        internal static string pvpAutoRotationWarning {
            get {
                return ResourceManager.GetString("pvpAutoRotationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are PvP features. They will only work in PvP-enabled zones..
        /// </summary>
        internal static string pvpDesc {
            get {
                return ResourceManager.GetString("pvpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing matched your search..
        /// </summary>
        internal static string pvpNothing {
            get {
                return ResourceManager.GetString("pvpNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a job from below to enable and configure features for it..
        /// </summary>
        internal static string SelectAJob {
            get {
                return ResourceManager.GetString("SelectAJob", resourceCulture);
            }
        }
    }
}
