//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.UI.MainWindow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.UI.MainWindow.MainWindow", typeof(MainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following plugins are known to conflict with {0}:
        ///
        ///{1}
        ///
        ///It is recommended you disable these plugins, or their rotation
        ///components, to prevent unexpected behavior and bugs..
        /// </summary>
        internal static string Tooltip_ConflictingPlugins {
            get {
                return ResourceManager.GetString("Tooltip_ConflictingPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following plugins are known to conflict with
        ///{0}&apos;s Settings, which you have enabled:
        ///{1}
        ///
        ///It is recommended you disable these plugins, or
        ///remove the conflicting setting in the plugins
        ///to prevent unexpected behavior and bugs..
        /// </summary>
        internal static string Tooltip_ConflictingPluginSettings {
            get {
                return ResourceManager.GetString("Tooltip_ConflictingPluginSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following Wrath settings are known to conflict with {0}&apos;s Settings:
        ///{1}
        ///
        ///It is recommended you disable these settings to prevent unexpected behavior and bugs..
        /// </summary>
        internal static string Tooltip_ConflictingWrathSettings {
            get {
                return ResourceManager.GetString("Tooltip_ConflictingWrathSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Setting: {0}
        ///    Problem: {1}.
        /// </summary>
        internal static string Tooltip_Conflicts_Reason {
            get {
                return ResourceManager.GetString("Tooltip_Conflicts_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have conflict(s) in your Dalamud config:
        ///.
        /// </summary>
        internal static string Tooltip_DalamudConfigConflicts {
            get {
                return ResourceManager.GetString("Tooltip_DalamudConfigConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following game settings are known to conflict with {0}&apos;s Settings:
        ///{1}
        ///
        ///It is recommended you change these settings to prevent unexpected behavior and bugs..
        /// </summary>
        internal static string Tooltip_GameConflicts {
            get {
                return ResourceManager.GetString("Tooltip_GameConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your configuration in the following plugins will conflict
        ///with {0}&apos;s enabled Action Retargeting:
        ///{1}
        ///
        ///It is recommended you disable these plugins, or
        ///remove the conflicting actions from their settings, or
        ///disable Retargeting for the action in {0},
        ///to prevent unexpected behavior and bugs..
        /// </summary>
        internal static string Tooltip_TargettingConflicts {
            get {
                return ResourceManager.GetString("Tooltip_TargettingConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         - {0}.
        /// </summary>
        internal static string Tooltip_TargettingConflicts_Action {
            get {
                return ResourceManager.GetString("Tooltip_TargettingConflicts_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0} {1}
        ///    Actions Retargeted there and in {2}:
        ///{3}.
        /// </summary>
        internal static string Tooltip_TargettingConflicts_Plugin {
            get {
                return ResourceManager.GetString("Tooltip_TargettingConflicts_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown conflict type:.
        /// </summary>
        internal static string Warning_UnknownConflictType {
            get {
                return ResourceManager.GetString("Warning_UnknownConflictType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrath Combo.
        /// </summary>
        internal static string Wrath_Combo {
            get {
                return ResourceManager.GetString("Wrath_Combo", resourceCulture);
            }
        }
    }
}
